### ISSUE TITLE
NameError: name 'FileNotFoundError' is not defined - cannot  import sklift in Jupyter Notebook 

### ISSUE THREAD

**Issue by lucre5** [maks-sh/scikit-uplift#21]
## ModuleNotFoundError Sklift even though scikit-uplift is installed

 I have installed the scikit-uplift with pip3 and I see it is in the correct directory for my Anaconda Jupyter Notebook. However, when I try to import it in Jupyter I get the ModuleNotFoundError: No module named 'sklift'. I then re-installed the package from the Github source as it is said in the docs, and I get the same error.

## To Reproduce
After installation I try to run `from sklift.metrics import uplift_at_k` but I get `ModuleNotFoundError: No module named 'sklift'`. I checked and the package is correctly installed, I restarted the notebook and it still didn't work. 

I decided to reinstall it from source, and now when I run `python setup.py install` in the scikit-uplift directory in terminal, I get

`File "setup.py", line 24, in <module>
    except FileNotFoundError:
NameError: name 'FileNotFoundError' is not defined`

##Edit 
If I run `python3 setup.py install` I get this warning:

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va
         cwd: /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/
    Complete output (64 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    
    Edit setup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)  [Clang 6.0
                      (clang-600.0.57)]]
        platform: yes [darwin]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]
    
    running egg_info
    creating /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info
    writing /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info/namespace_packages.txt
    writing requirements to /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info/requires.txt
    writing top-level names to /private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-pip-egg-info-adyt94va/matplotlib.egg-info/SOURCES.txt'
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "/private/var/folders/b3/v9dt6kxj0fx7k40tn4ppx6t40000gn/T/pip-install-gwr73n6u/matplotlib/.eggs/numpy-1.19.2-py3.9-macosx-10.9-x86_64.egg/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Environment
 - scikit-uplift (0.2.0):
 - scikit-learn (0.22.1):
 - Python (3.9):
 - OS (MacOS)

**Comment by maks-sh** [comment]
Hi!

Thanks for the bug report.

Due to error looks like you are trying to install the package with python 2.

I recommend using the following command directly from jupyter to install the package in the required python environment:

```
import sys
!{sys.executable} -m pip install scikit-uplift
```
 
So, `sys.executable` returns the right path to the Python that is used in the jupyter kernel, which you could use in your terminal.

**Comment by lucre5** [comment]
Hello,

thank you so much for the fast reply! That fixed it. Hope you have a great day!
